apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: broker-persistent-volume-claim
      containers:
        - name: kafka
          image: bitnami/kafka:2.5.0
          ports:
            - containerPort: 9092
              hostPort: 9092
          volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami/kafka
              subPath: data/kafka
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: ZOOKEEPER_PORT
              value: '2181'
            - name: ZOOKEEPER_HOST
              value: zookeeper-cluster-ip-service
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-cluster-ip-service:2181
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: zookeeper-cluster-ip-service:2181
