export const newspapers = {
  PUBLICO: "PUBLICO",
  OBSERVADOR: "OBSERVADOR",
};

export const topics = newspapers;

export const messages = {
  PUBLICO: {
    RETRIEVE_PAGE: "RETRIEVE_PAGE",
    RETRIEVED_PAGE_DATA: "PAGE_DATA",
    RETRIEVE_ARTICLE: "RETRIEVE_ARTICLE",
    RETRIEVED_ARTICLE_DATA: "ARTICLE_DATA",
    RETRIEVE_PAGE_OLDEST_ARTICLE: "RETRIEVE_PAGE_OLDEST_ARTICLE",
    RETRIEVED_PAGE_OLDEST_ARTICLE_DATA: "RETRIEVED_PAGE_OLDEST_ARTICLE_DATA",
  },
  OBSERVADOR: {
    RETRIEVE_MOST_RECENT_ARTICLE: "RETRIEVE_MOST_RECENT_ARTICLE",
    RETRIEVED_MOST_RECENT_ARTICLE_DATA: "MOST_RECENT_ARTICLE_DATA",
    FILTER_ARTICLES: "FILTER_ARTICLES",
    FILTERED_ARTICLE_DATA: "FILTERED_ARTICLE_DATA",
    RETRIEVE_ARTICLE: "RETRIEVE_ARTICLE",
    RETRIEVED_ARTICLE_DATA: "ARTICLE_DATA",
  }
};

export const publico = {
  lastPage: 69200
};