apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zookeeper/registry-persistent-volume-claim.yaml
  - zookeeper/zookeeper-cluster-ip-service.yaml
  - zookeeper/zookeeper-deployment.yaml

  - kafka/broker-persistent-volume-claim.yaml
  - kafka/kafka-cluster-ip-service.yaml
  - kafka/kafka-deployment.yaml

  - manager/manager-cluster-ip-service.yaml
  - manager/manager-deployment.yaml

  - worker/worker-cluster-ip-service.yaml
  - worker/worker-deployment.yaml

  - entities/entities-cluster-ip-service.yaml
  - entities/entities-deployment.yaml
